###

GET https://atlasion.onrender.com/users

###

POST https://atlasion.onrender.com/register
Content-Type: application/json

   {
      "username": "Admin",
      "password": "Admin@123",
      "email": "Admin123@example.com",
      "firstName": "AryanKumar",
      "lastName": "Bhadhoriya",
      "age": 28
    }

###

POST https://atlasion.onrender.com/login
Content-Type: application/json

{
    "email":"tash@gmail.com",
    "password":"tashwini13"
}
