###

GET https://atlasion.onrender.com/users

###

POST https://atlasion.onrender.com/register
Content-Type: application/json

    {
      "username": "codingNinja",
      "password": "code456",
      "email": "codingninja@example.com",
      "firstName": "Noah",
      "lastName": "Hernandez",
      "age": 28
    }

###

POST https://atlasion.onrender.com/login
Content-Type: application/json

{
    "email":"tash@gmail.com",
    "password":"tashwini13"
}
