###

GET https://atlasion.onrender.com/users

###

POST http://localhost:4000/register
Content-Type: Application/json

   {
      "username": "Admin",
      "password": "Admin@123",
      "email": "Admin123@example.com",
      "firstName": "AryanKumar",
      "lastName": "Bhadhoriya",
      "age": 28
    }

###

POST https://atlasion.onrender.com/login
Content-Type: Application/json

{
    "email":"Admin123@example.com",
    "password":"Admin@123"
}
